### ISSUE TITLE
Show Last updated by Information in Web IDE

### ISSUE THREAD

**Issue by dbtutor** [coltonfischer/ps-web-ide#1]
It would be nice to have to show - "Last updated by" at the bottom.
![image](https://user-images.githubusercontent.com/626498/85255376-ce1bdc00-b47f-11ea-99b7-634a626cb05d.png)

Thanks,

**Comment by coltonfischer** [comment]
Thanks for the feature suggestion. The latest release of the project contains this feature.  You should now see the last updated by information in the bottom right corner when viewing an object.

![image](https://user-images.githubusercontent.com/24225396/99996331-2fbeda00-2d81-11eb-95b4-f3b8cb226fc2.png)
