### ISSUE TITLE
The page is blank,JS error

### ISSUE THREAD

**Issue by josefly567** [coltonfischer/ps-web-ide#2]
I opened Web IDE, but there was nothing. It reported a mistake,the third party does not seem to be in effect

<img width="1778" alt="Snipaste_2020-11-10_14-53-49" src="https://user-images.githubusercontent.com/29234896/98640779-9bf31400-2365-11eb-84fb-a1dd67624f48.png">

**Comment by coltonfischer** [comment]
Thanks for bringing this to my attention.  I was able to replicate this issue in one of my environments and the problem appears to be related to how PeopleSoft minifies JavaScript.  For a workaround you can navigate to the Web Profile Configuration page and check the "Use Unminified JavaScript" box under the debugging tab.  A web server restart will be required.

I will look into delivering the assets in this project as unminified so there is no conflict with PeopleSoft minification.

**Comment by coltonfischer** [comment]
I was able to determine the parts of the JavaScript that were causing the PeopleSoft minification process to corrupt the files.  There were some inline comments that I had to remove.  I exported the project and plan to update the repo with a new release. 

Here is the new App Designer project: [1.0.3.zip](https://github.com/coltonfischer/ps-web-ide/files/5526501/1.0.3.zip)

**Comment by josefly567** [comment]
Thank you for answering my question
